//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prCCCmp.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRCCCMP_H)
#define _PRCCCMP_H

#include <per/prFeaturesComparator.h>

template<typename T>
class prCCCmp : public prFeaturesComparator<T>
{

};

#endif  //_PRCCCMP_H
