//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prDirectCmp.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRDIRECTCMP_H)
#define _PRDIRECTCMP_H

#include <per/prFeaturesComparator.h>

template<typename T>
class prDirectCmp : public prFeaturesComparator<T> {
};

#endif  //_PRDIRECTCMP_H
