//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prModelsParametersOptimization.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRMODELSPARAMETERSESTIMATION_H)
#define _PRMODELSPARAMETERSESTIMATION_H


class prModelsParametersEstimation {
};

#endif  //_PRMODELSPARAMETERSESTIMATION_H
