//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prPhaseCorrelationCmp.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRPHASECORRELATIONCMP_H)
#define _PRPHASECORRELATIONCMP_H

#include <per/prFeaturesComparator.h>

template<typename T>
class prPhaseCorrelationCmp : public prFeaturesComparator<T>
{
};

#endif  //_PRPHASECORRELATIONCMP_H
