//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prZNCCCmp.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRZNCCCMP_H)
#define _PRZNCCCMP_H

#include <per/prCCCmp.h>

template<typename T>
class prZNCCCmp : public prCCCmp<T>
{
};

#endif  //_PRZNCCCMP_H
