//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prZNSSDCmp.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRZNSSDCMP_H)
#define _PRZNSSDCMP_H

#include <per/prSSDCmp.h>

template<typename T>
class prZNSSDCmp : public prSSDCmp<T> {
};

#endif  //_PRZNSSDCMP_H
