//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : pr3DPose.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PR3DPOSE_H)
#define _PR3DPOSE_H

#include <per/prFeature.h>

class pr3DPose : public prFeature {
};

#endif  //_PR3DPOSE_H
