//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : pr3DDistance.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PR3DDISTANCE_H)
#define _PR3DDISTANCE_H

#include <per/prFeature.h>

class pr3DDistance : public prFeature {
};

#endif  //_PR3DDISTANCE_H
