//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prEntropy.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRENTROPY_H)
#define _PRENTROPY_H

#include <per/prFeature.h>

class prEntropy : public prFeature {
};

#endif  //_PRENTROPY_H
