//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prGrayLevel.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRGRAYLEVEL_H)
#define _PRGRAYLEVEL_H

#include <per/prIntensity.h>

class prGrayLevel : public prIntensity {
};

#endif  //_PRGRAYLEVEL_H
