//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prPatchPoint.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRPATCHPOINT_H)
#define _PRPATCHPOINT_H

#include <per/prPatch.h>
#include <per/prPointFeature.h>

class prPatchPoint : public prPatch, public prPointFeature {
};

#endif  //_PRPATCHPOINT_H
