//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prPatchPlane.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRPATCHPLANE_H)
#define _PRPATCHPLANE_H

#include <per/prPatch.h>

class prPatchPlane : public prPatch {
};

#endif  //_PRPATCHPLANE_H
