//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prPatch.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRPATCH_H)
#define _PRPATCH_H

#include <per/prFeature.h>

class prPatch : public prFeature {
};

#endif  //_PRPATCH_H
