//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prPhotometricEntropy.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRPHOTOMETRICENTROPY_H)
#define _PRPHOTOMETRICENTROPY_H

#include <per/prEntropy.h>

class prPhotometricEntropy : public prEntropy {
};

#endif  //_PRPHOTOMETRICENTROPY_H
