//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prSalientGMS.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRSALIENTGMS_H)
#define _PRSALIENTGMS_H

#include <per/prGaussianMixtureSample.h>

class prSalientGMS /*: public prGaussianMixtureSample*/ {
};

#endif  //_PRSALIENTGMS_H
