//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prCameraModelOpt.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRCAMERAMODELOPT_H)
#define _PRCAMERAMODELOPT_H

#include <per/prSensorModelOpt.h>

class prCameraModelOpt : public prSensorModelOpt {
};

#endif  //_PRCAMERAMODELOPT_H
