//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prEquirectangularOpt.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PREQUIRECTANGULAROPT_H)
#define _PREQUIRECTANGULAROPT_H

#include <per/prCameraModelOpt.h>

class prEquirectangularOpt : public prCameraModelOpt {
};

#endif  //_PREQUIRECTANGULAROPT_H
