//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prLocalizedSensorOpt.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRLOCALIZEDSENSOROPT_H)
#define _PRLOCALIZEDSENSOROPT_H

#include <per/prModelsParametersEstimation.h>

class prLocalizedSensorOpt : public prModelsParametersEstimation {
};

#endif  //_PRLOCALIZEDSENSOROPT_H
