//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prOmniOpt.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PROMNIOPT_H)
#define _PROMNIOPT_H

#include <per/prCameraModelOpt.h>

class prOmniOpt : public prCameraModelOpt {
};

#endif  //_PROMNIOPT_H
