//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prParaboloidOpt.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRPARABOLOIDOPT_H)
#define _PRPARABOLOIDOPT_H

#include <per/prCameraModelOpt.h>

class prParaboloidOpt : public prCameraModelOpt {
};

#endif  //_PRPARABOLOIDOPT_H
