//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prPerspectiveOpt.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRPERSPECTIVEOPT_H)
#define _PRPERSPECTIVEOPT_H

#include <per/prCameraModelOpt.h>

class prPerspectiveOpt : public prCameraModelOpt {
};

#endif  //_PRPERSPECTIVEOPT_H
