//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prSensorModelOpt.h
//  @ Date : 16/01/2017
//  @ Author :
//
//


#if !defined(_PRSENSORMODELOPT_H)
#define _PRSENSORMODELOPT_H

#include <per/prModelsParametersEstimation.h>

class prSensorModelOpt : public prModelsParametersEstimation {
};

#endif  //_PRSENSORMODELOPT_H
