//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prContour.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRCONTOUR_H)
#define _PRCONTOUR_H

#include <per/prFeatureExtraction.h>

class prContour : public prFeatureExtraction {
};

#endif  //_PRCONTOUR_H
