//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prDot.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRDOT_H)
#define _PRDOT_H

#include <per/prContour.h>
#include <per/prKeyPoint.h>

class prDot : public prContour, public prKeyPoint {
};

#endif  //_PRDOT_H
