//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prFeatureExtraction.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRFEATUREEXTRACTION_H)
#define _PRFEATUREEXTRACTION_H


class prFeatureExtraction {
};

#endif  //_PRFEATUREEXTRACTION_H
