//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prImageFilter.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRIMAGEFILTER_H)
#define _PRIMAGEFILTER_H


class prImageFilter {
};

#endif  //_PRIMAGEFILTER_H
