//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prKeyPointHarris.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRKEYPOINTHARRIS_H)
#define _PRKEYPOINTHARRIS_H

#include <per/prKeyPoint.h>

class prKeyPointHarris : public prKeyPoint {
};

#endif  //_PRKEYPOINTHARRIS_H
