//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prKeyPoint.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRKEYPOINT_H)
#define _PRKEYPOINT_H

#include <per/prFeatureExtraction.h>

class prKeyPoint : public prFeatureExtraction {
};

#endif  //_PRKEYPOINT_H
