//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prKeyPointASIFT.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRKEYPOINTASIFT_H)
#define _PRKEYPOINTASIFT_H

#include <per/prKeyPoint.h>

class prKeyPointASIFT : public prKeyPoint {
};

#endif  //_PRKEYPOINTASIFT_H
