//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prRing.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRRING_H)
#define _PRRING_H

#include <per/prDot.h>

class prRing : public prDot {
};

#endif  //_PRRING_H
