//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prMESH.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRMESH_H)
#define _PRMESH_H

#include <per/prIo.h>

class prMESH : public prIo {
};

#endif  //_PRMESH_H
