//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prPCD.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRPCD_H)
#define _PRPCD_H

#include <per/prIo.h>

class prPCD : public prIo {
};

#endif  //_PRPCD_H
