//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prPLY.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRPLY_H)
#define _PRPLY_H

#include <per/prIo.h>

class prPLY : public prIo {
};

#endif  //_PRPLY_H
