//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prPTS.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRPTS_H)
#define _PRPTS_H

#include <per/prIo.h>

class prPTS : public prIo {
};

#endif  //_PRPTS_H
