//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prPTX.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRPTX_H)
#define _PRPTX_H

#include <per/prIo.h>

class prPTX : public prIo {
};

#endif  //_PRPTX_H
