//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prCameraPoseOpt.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRCAMERAPOSEESTIM_H)
#define _PRCAMERAPOSEESTIM_H

#include <per/prPoseEstim.h>

class prCameraPoseEstim : public prPoseEstim {
};

#endif  //_PRCAMERAPOSEESTIM_H
