//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prPoseParaboloidOpt.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRPOSEPARABOLOIDESTIM_H)
#define _PRPOSEPARABOLOIDESTIM_H

#include <per/prPoseEstim.h>
#include <per/prCameraPoseEstim.h>

class prPoseParaboloidEstim : public prCameraPoseEstim {
};

#endif  //_PRPOSEPARABOLOIDESTIM_H
