//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prPoseOmniOpt.h
//  @ Date : 16/01/2017
//  @ Author :
//
//


#if !defined(_PRPOSEESTIM_H)
#define _PRPOSEESTIM_H

#include <per/prModelsParametersEstimation.h>

class prPoseEstim : public prModelsParametersEstimation {
};

#endif  //_PRPOSEOMNIESTIM_H
