//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prPosePerspectiveOpt.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRPOSEPERSPECTIVEESTIM_H)
#define _PRPOSEPERSPECTIVEESTIM_H

#include <per/prCameraPoseEstim.h>

class prPosePerspectiveEstim : public prCameraPoseEstim {
};

#endif  //_PRPOSEPERSPECTIVEESTIM_H
