//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prPoseOmniOpt.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRPOSEOMNIESTIM_H)
#define _PRPOSEOMNIESTIM_H

#include <per/prCameraPoseEstim.h>

class prPoseOmniEstim : public prCameraPoseEstim {
};

#endif  //_PRPOSEOMNIESTIM_H
