//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : prWorldModelOpt.h
//  @ Date : 16/01/2017
//  @ Author : 
//
//


#if !defined(_PRWORLDMODELOPT_H)
#define _PRWORLDMODELOPT_H

#include <per/prModelsParametersEstimation.h>

class prWorldModelOpt : public prModelsParametersEstimation {
};

#endif  //_PRWORLDMODELOPT_H
